### ISSUE TITLE
daily build is run in PRs and master

### ISSUE THREAD

**Issue by jnothman** [MacPython/scikit-learn-wheels#20]
It should only be run on daily build jobs.

Ping @thomasjpfan 

Not sure if this has anything to do with me not being able to `fetch_artifacts` for the 0.20.3 release just merged.

**Comment by jnothman** [comment]
I ping you, though you're better off going and seeing Paris, Thomas :)

**Comment by jnothman** [comment]
The logs on my recent merge to master look very different to the previous release. We seem to not be doing the right thing when `DAILY_BUILD=false`: I'm not seeing a full build on the release CI.

**Comment by thomasjpfan** [comment]
I am looking into this issue.
