### ISSUE TITLE
Add a build for the source distribution

### ISSUE THREAD

**Issue by jnothman** [MacPython/scikit-learn-wheels#31]
It seems silly that:
* the nightly builds do not include an sdist (to avoid users having to cythonize)
* the release maintainer needs to build the sdist separate from the wheels.

We should have a job here that uploads an sdist alongside the wheels... as long as that then works with `fetch_artifacts`.

**Comment by rth** [comment]
+1.

Do we still want to cythonize in sdists though? It's seems like Cython generated .c files is not forward compatible with future Python versions, and if I remember correctly there were several issues reported about it. Adding cython to build requirements (or what goes for it pre [PEP 518](https://www.python.org/dev/peps/pep-0518/)) could be a workaround.

**Comment by ogrisel** [comment]
Good remark for Cython but this is a separate issue: we still have it if we do the sdist manually.

**Comment by ogrisel** [comment]
+1 for automating the generation of the sdist archive. That would also give us the ability to test installation from the source tarball. We could also run `twine check` on it.

**Comment by jnothman** [comment]
Yes, we've messed up sdist generation before.
