### ISSUE TITLE
Use a minimal Windows docker container to check the wheels

### ISSUE THREAD

**Issue by ogrisel** [MacPython/scikit-learn-wheels#44]
Such a minimal windows test environment should have no C/C++ compiler installed, nor SDK, nor redistributable runtime such as `c:\Windows\System32\vcomp140.dll` nor even Miniconda. Indeed Miniconda ships its own bunch of system dlls such as vcomp140.dll by default.

The goal would be to detect problems such as https://github.com/scikit-learn/scikit-learn/issues/15899 before releasing.

Instead it should install Python from https://www.python.org (e.g. an embedded zip or from the .msi installer which can be installed from the command line).

We should probably do that based on #23 as the current AppVeyor worker is really too slow to iterate with.

A minimal test environment is probably achievable using a Windows `servercore` container although I have never tried myself.

## References

Powershell script to download install python .msi from python.org:
https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor/install.ps1#L104

Windows containers on Azure Pipelines:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#windows-containers

**Comment by thomasjpfan** [comment]
I agree this would be good.

I will update #23 when https://github.com/MacPython/scikit-learn-wheels/pull/43 and https://github.com/scikit-learn/scikit-learn/pull/15929 gets resolved.

**Comment by jnothman** [comment]
Should this be contributed back to multibuild?

**Comment by ogrisel** [comment]
Indeed, although it might be CI platform specific.

**Comment by ogrisel** [comment]
Now that we have switched to use cibuildwheel in the master repo, we might want to develop this there instead.

**Comment by ogrisel** [comment]
cc @alfaro96.

**Comment by alfaro96** [comment]
Is the idea to have a [Windows Docker container (`servercore`)](https://hub.docker.com/_/microsoft-windows-servercore) to manually install `Python` (using a `.zip` or `.msi` file) and then install the (Windows) wheels and run the tests to ensure that we properly vendor the `vcomp140.dll` file?
