### ISSUE TITLE
Add python 3.7 support

### ISSUE THREAD

**Issue by rth** [MacPython/scikit-learn-wheels#5]
For the next v0.20 release it would be helpful to add python 3.7 support (related https://github.com/scikit-learn/scikit-learn/issues/11396).

Python 3.7 was recently added in the manylinux repo (https://github.com/matthew-brett/multibuild) and its submodule used  here maybe could be updated. I'm not sure sure what need to be done on the appveyor side..

**Comment by ogrisel** [comment]
I pushed the Python 3.7 entries on master. However we still miss some binary wheels for Python 3.7 for numpy and scipy on some platforms.

**Comment by rth** [comment]
Closing as fixed.
