### ISSUE TITLE
Manylinux builds not using OpenBLAS

### ISSUE THREAD

**Issue by rth** [MacPython/scikit-learn-wheels#6]
As reported in https://github.com/scikit-learn/scikit-learn/issues/10105#issuecomment-406412870 by @jakirkham , the manylinux wheels generated for 0.19.2 (and possibly earlier ones as well) do not seem to be using OpenBLAS, and instead fallback to the bundled CBLAS. 

Generally is there any documentation about this (except for the one on numpy/scipy issue trackers and mailing lists)?

**Comment by ogrisel** [comment]
We would have to adapt this build configuration to replicate the numpy and scipy's so as to build against a copy of OpenBLAS and then include it in the resulting wheel. More details in the numpy wheels build config: https://github.com/MacPython/numpy-wheels

On windows, we would have then make sure to include the DLL into the windows wheel. I think this is a manual operation and can be tricky to get right: we need to put in the same subfolder as the first binary extension that is imported when we import sklearn. I think `sklearn/__check_build/` would work but I am not 100% sure.

For macOS and linux it should be easier thanks to the  `auditwheel` tools can be used to automate this embedding of the dll into the wheel.

**Comment by ogrisel** [comment]
However, as said earlier, once we bump up the scipy dependency, we could `cimport` BLAS functions from scipy instead of building against our own copy of openblas. In this case we would not need to embed openblas anymore.

**Comment by rth** [comment]
Thanks for all the useful information! I guess it's more a question if someone investigates this before the 0.21 release when the scipy's BLAS API could be used...

**Comment by ogrisel** [comment]
Now that 0.21rc2 is building with scipy BLAS, I think we can close this issue.
