### ISSUE TITLE
Investigate cibuildwheel

### ISSUE THREAD

**Issue by rth** [MacPython/scikit-learn-wheels#61]
I recently added a setup to  build wheels in https://github.com/scikit-learn-contrib/scikit-learn-extra/pull/66 with [cibuildwheel](https://github.com/joerick/cibuildwheel) and it was pleasantly straightforward. Or maybe I haven't run into issues yet )

In any case I think it might be worth considering it for scikit-learn. We could also add it to the main repo (related to https://github.com/MacPython/scikit-learn-wheels/issues/27) and build wheels on tags. It would very easy to test before the release just by uncommenting some CI config lines in a PR.  It's probably a bit less flexible that our current setup, but it might be sufficient.

In the long run it would also allow building wheels for other architecture (aarc64, ppc64le) or Python distributions (PyPy), if we want to do that.

Unless there some blocker that would prevent us from using it?

**Comment by jnothman** [comment]
Sounds worthwhile to try, to avoid this separate repo and process.

**Comment by alfaro96** [comment]
If you think it is okay, I may open a (Draft) PR in the [scikit-learn repository](https://github.com/scikit-learn/scikit-learn) to investigate how [`cibuildwheel`](https://github.com/joerick/cibuildwheel) performs.

**Comment by rth** [comment]
That would be great @alfaro96 ! We could probably try with Github Actions there.

**Comment by thomasjpfan** [comment]
I suspect that integrating https://github.com/MacPython/scikit-learn-wheels/blob/master/azure/vendor_vcomp140.py with `cibuildwheel` may be nontrival.
