### ISSUE TITLE
Update to manylinux2010

### ISSUE THREAD

**Issue by rth** [MacPython/scikit-learn-wheels#62]
From https://www.python.org/dev/peps/pep-0571/#id48

> CentOS 5.11 [used to build manylinux1] reached its end-of-life on March 31st, 2017 with a clear warning against its continued use

Should we update the wheels to manylinux2010? Or at least would it be OK to build manylinux2010 directly in https://github.com/scikit-learn/scikit-learn/pull/17921#discussion_r454248895 ?

BTW, 
> CentOS 6 [used for manylinux2010] is now the oldest supported CentOS release, and will receive maintenance updates through November 30th, 2020.

In general, are there some guidelines as to when one should update the manylinux version?

**Edit:** I guess the thread from https://github.com/pypa/manylinux/issues/179#issuecomment-520512039 answers some of these questions.

In particular manylinux2010 would require pip > 19.0

**Comment by mattip** [comment]
You can use multibuild to build and test any current manylinux wheel, including arm64 and pypy. Over at numpy-wheels we are using travis (for arm64 and pypy linux64) and azure (for all the rest), and we ship manylinux1 (for legacy), manylinux2010 (which is the majority) and manylinux2014 for arm64.

**Comment by thomasjpfan** [comment]
On numpy-wheels are you able to build and run the complete test suite when building for arm64?

**Comment by mattip** [comment]
[Yup](https://travis-ci.org/github/MacPython/numpy-wheels/builds/704971979) (I hope you can see the link to the test-runs). But the runs are about 2x slower than our [azure ones](https://dev.azure.com/numpy/numpy/_build/results?buildId=11166&view=results)

**Comment by ogrisel** [comment]
The new [cibuildwheel-based system](https://github.com/scikit-learn/scikit-learn/blob/master/.github/workflows/wheels.yml) in scikit-learn master is already building 2010 wheel by default. I don't think we need to generate manylinux1 wheels for scikit-learn anymore.
