### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by mattip** [MacPython/scikit-learn-wheels#67]
Can we archive this repo? Many of the multibuild projects under this org have moved to cibuildwheel, and now build via CI jobs on the main repo. Is this true of scikit-learn?

**Comment by thomasjpfan** [comment]
Yes it is true, scikit-learn has also moved to `cibuildwheel` and no longer uses this repo for building wheels. I am +1 on archiving this repo.

**Comment by mattip** [comment]
Thanks, I will archive it.
